#!/bin/bash

BASEDIR=$(dirname "$0")
SCRIPT_PATH="$BASEDIR/pre-push.d"

for hook in ${SCRIPT_PATH}/*; do
  if [ -f "${hook}" ]; then
    echo "Running hook: $hook"
    "${hook}"

    if [ $? != 0 ]; then
      exit 1
    fi
  else
    echo "Error: file ${hook} not found."
    echo "Aborting commit. Make sure the hook is in $(${SCRIPT_PATH}) and executable."
    echo "You can skip all pre-commit hooks with --no-verify (not recommended)."
    exit 1
  fi
done
