doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: pdo_pgsql
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci
    types:
      uuid: Ramsey\Uuid\Doctrine\UuidType
      datetime_immutable: App\Infrastructure\Persistence\Doctrine\Types\DateTimeType
      experience: App\Infrastructure\Persistence\Doctrine\Types\ExperienceType
      money: App\Infrastructure\Persistence\Doctrine\Types\MoneyType
      slug: App\Infrastructure\Persistence\Doctrine\Types\SlugType

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/App/Domain/Entity'
        prefix: 'App\Domain\Entity'
        alias: App

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
