doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: pdo_pgsql
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci
    types:
      uuid: App\Shared\Infrastructure\Persistence\Doctrine\Types\UuidType
      datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
      experience: App\Shared\Infrastructure\Persistence\Doctrine\Types\ExperienceType
      money: App\Shared\Infrastructure\Persistence\Doctrine\Types\MoneyType
      slug: App\Shared\Infrastructure\Persistence\Doctrine\Types\SlugType

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/App/User/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: 'App\User\Domain\Entity'
        alias: User
      Game:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/App/Game/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: 'App\Game\Domain\Entity'
        alias: Game

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
