name: Audit

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Update composer
        run: composer self-update
        working-directory: api

      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        working-directory: api

      - name: PHPLint
        run: composer run phplint
        working-directory: api

      - name: PHP-CS-fixer
        run: composer run php-cs-fixer fix -- --dry-run --diff
        working-directory: api

      - name: Static analysis
        run: composer run psalm -- --shepherd --stats
        working-directory: api

      - name: Copy .phpunit.xml
        run: cp phpunit.xml.dist phpunit.xml
        working-directory: api

      - name: Unit tests
        run: composer run test -- --group=unit
        working-directory: api
