version: "3.9"

services:
  php-fpm:
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      APP_ENV: "dev"
      APP_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      APP_ENV: "dev"
      APP_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
